/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125AuthRouteImport } from './routes/{-$locale}/auth'
import { Route as Char123LocaleChar125MarketingRouteImport } from './routes/{-$locale}/_marketing'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/_dashboard'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as Char123LocaleChar125MarketingIndexRouteImport } from './routes/{-$locale}/_marketing/index'
import { Route as Char123LocaleChar125DemoBetterAuthRouteImport } from './routes/{-$locale}/demo/better-auth'
import { Route as Char123LocaleChar125AuthResetPasswordRouteImport } from './routes/{-$locale}/auth/reset-password'
import { Route as Char123LocaleChar125AuthRegisterSuccessRouteImport } from './routes/{-$locale}/auth/register-success'
import { Route as Char123LocaleChar125AuthRegisterRouteImport } from './routes/{-$locale}/auth/register'
import { Route as Char123LocaleChar125AuthLoginRouteImport } from './routes/{-$locale}/auth/login'
import { Route as Char123LocaleChar125AuthForgotPasswordRouteImport } from './routes/{-$locale}/auth/forgot-password'
import { Route as Char123LocaleChar125AuthConfirmRouteImport } from './routes/{-$locale}/auth/confirm'
import { Route as Char123LocaleChar125MarketingPaySuccessRouteImport } from './routes/{-$locale}/_marketing/pay-success'
import { Route as Char123LocaleChar125MarketingContactRouteImport } from './routes/{-$locale}/_marketing/contact'
import { Route as Char123LocaleChar125MarketingAboutRouteImport } from './routes/{-$locale}/_marketing/about'
import { Route as ApiUserSubscriptionRouteImport } from './routes/api/user/subscription'
import { Route as ApiUserSettingsRouteImport } from './routes/api/user/settings'
import { Route as ApiUserProfileRouteImport } from './routes/api/user/profile'
import { Route as ApiUserBillingRouteImport } from './routes/api/user/billing'
import { Route as ApiPaymentQueryRouteImport } from './routes/api/payment/query'
import { Route as ApiPaymentCreateRouteImport } from './routes/api/payment/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as Char123LocaleChar125DashboardDashboardIndexRouteImport } from './routes/{-$locale}/_dashboard/dashboard/index'
import { Route as ApiPaymentNotifyCreemRouteImport } from './routes/api/payment/notify/creem'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AuthRoute =
  Char123LocaleChar125AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125MarketingRoute =
  Char123LocaleChar125MarketingRouteImport.update({
    id: '/_marketing',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125MarketingIndexRoute =
  Char123LocaleChar125MarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MarketingRoute,
  } as any)
const Char123LocaleChar125DemoBetterAuthRoute =
  Char123LocaleChar125DemoBetterAuthRouteImport.update({
    id: '/demo/better-auth',
    path: '/demo/better-auth',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthResetPasswordRoute =
  Char123LocaleChar125AuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthRegisterSuccessRoute =
  Char123LocaleChar125AuthRegisterSuccessRouteImport.update({
    id: '/register-success',
    path: '/register-success',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthRegisterRoute =
  Char123LocaleChar125AuthRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthLoginRoute =
  Char123LocaleChar125AuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthForgotPasswordRoute =
  Char123LocaleChar125AuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthConfirmRoute =
  Char123LocaleChar125AuthConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125MarketingPaySuccessRoute =
  Char123LocaleChar125MarketingPaySuccessRouteImport.update({
    id: '/pay-success',
    path: '/pay-success',
    getParentRoute: () => Char123LocaleChar125MarketingRoute,
  } as any)
const Char123LocaleChar125MarketingContactRoute =
  Char123LocaleChar125MarketingContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125MarketingRoute,
  } as any)
const Char123LocaleChar125MarketingAboutRoute =
  Char123LocaleChar125MarketingAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125MarketingRoute,
  } as any)
const ApiUserSubscriptionRoute = ApiUserSubscriptionRouteImport.update({
  id: '/api/user/subscription',
  path: '/api/user/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSettingsRoute = ApiUserSettingsRouteImport.update({
  id: '/api/user/settings',
  path: '/api/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserBillingRoute = ApiUserBillingRouteImport.update({
  id: '/api/user/billing',
  path: '/api/user/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentQueryRoute = ApiPaymentQueryRouteImport.update({
  id: '/api/payment/query',
  path: '/api/payment/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateRoute = ApiPaymentCreateRouteImport.update({
  id: '/api/payment/create',
  path: '/api/payment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125DashboardDashboardIndexRoute =
  Char123LocaleChar125DashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const ApiPaymentNotifyCreemRoute = ApiPaymentNotifyCreemRouteImport.update({
  id: '/api/payment/notify/creem',
  path: '/api/payment/notify/creem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125MarketingRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/query': typeof ApiPaymentQueryRoute
  '/api/user/billing': typeof ApiUserBillingRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/api/user/subscription': typeof ApiUserSubscriptionRoute
  '/{-$locale}/about': typeof Char123LocaleChar125MarketingAboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125MarketingContactRoute
  '/{-$locale}/pay-success': typeof Char123LocaleChar125MarketingPaySuccessRoute
  '/{-$locale}/auth/confirm': typeof Char123LocaleChar125AuthConfirmRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/auth/register': typeof Char123LocaleChar125AuthRegisterRoute
  '/{-$locale}/auth/register-success': typeof Char123LocaleChar125AuthRegisterSuccessRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/demo/better-auth': typeof Char123LocaleChar125DemoBetterAuthRoute
  '/{-$locale}/': typeof Char123LocaleChar125MarketingIndexRoute
  '/api/payment/notify/creem': typeof ApiPaymentNotifyCreemRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125DashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125MarketingIndexRoute
  '/api/contact': typeof ApiContactRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/query': typeof ApiPaymentQueryRoute
  '/api/user/billing': typeof ApiUserBillingRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/api/user/subscription': typeof ApiUserSubscriptionRoute
  '/{-$locale}/about': typeof Char123LocaleChar125MarketingAboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125MarketingContactRoute
  '/{-$locale}/pay-success': typeof Char123LocaleChar125MarketingPaySuccessRoute
  '/{-$locale}/auth/confirm': typeof Char123LocaleChar125AuthConfirmRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/auth/register': typeof Char123LocaleChar125AuthRegisterRoute
  '/{-$locale}/auth/register-success': typeof Char123LocaleChar125AuthRegisterSuccessRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/demo/better-auth': typeof Char123LocaleChar125DemoBetterAuthRoute
  '/api/payment/notify/creem': typeof ApiPaymentNotifyCreemRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/{-$locale}/_dashboard': typeof Char123LocaleChar125DashboardRouteWithChildren
  '/{-$locale}/_marketing': typeof Char123LocaleChar125MarketingRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/query': typeof ApiPaymentQueryRoute
  '/api/user/billing': typeof ApiUserBillingRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/api/user/subscription': typeof ApiUserSubscriptionRoute
  '/{-$locale}/_marketing/about': typeof Char123LocaleChar125MarketingAboutRoute
  '/{-$locale}/_marketing/contact': typeof Char123LocaleChar125MarketingContactRoute
  '/{-$locale}/_marketing/pay-success': typeof Char123LocaleChar125MarketingPaySuccessRoute
  '/{-$locale}/auth/confirm': typeof Char123LocaleChar125AuthConfirmRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/auth/register': typeof Char123LocaleChar125AuthRegisterRoute
  '/{-$locale}/auth/register-success': typeof Char123LocaleChar125AuthRegisterSuccessRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/demo/better-auth': typeof Char123LocaleChar125DemoBetterAuthRoute
  '/{-$locale}/_marketing/': typeof Char123LocaleChar125MarketingIndexRoute
  '/api/payment/notify/creem': typeof ApiPaymentNotifyCreemRoute
  '/{-$locale}/_dashboard/dashboard/': typeof Char123LocaleChar125DashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/api/contact'
    | '/{-$locale}/auth'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/payment/create'
    | '/api/payment/query'
    | '/api/user/billing'
    | '/api/user/profile'
    | '/api/user/settings'
    | '/api/user/subscription'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/pay-success'
    | '/{-$locale}/auth/confirm'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/register'
    | '/{-$locale}/auth/register-success'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/demo/better-auth'
    | '/{-$locale}/'
    | '/api/payment/notify/creem'
    | '/{-$locale}/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/api/contact'
    | '/{-$locale}/auth'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/payment/create'
    | '/api/payment/query'
    | '/api/user/billing'
    | '/api/user/profile'
    | '/api/user/settings'
    | '/api/user/subscription'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/pay-success'
    | '/{-$locale}/auth/confirm'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/register'
    | '/{-$locale}/auth/register-success'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/demo/better-auth'
    | '/api/payment/notify/creem'
    | '/{-$locale}/dashboard'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/api/contact'
    | '/{-$locale}/_dashboard'
    | '/{-$locale}/_marketing'
    | '/{-$locale}/auth'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/payment/create'
    | '/api/payment/query'
    | '/api/user/billing'
    | '/api/user/profile'
    | '/api/user/settings'
    | '/api/user/subscription'
    | '/{-$locale}/_marketing/about'
    | '/{-$locale}/_marketing/contact'
    | '/{-$locale}/_marketing/pay-success'
    | '/{-$locale}/auth/confirm'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/register'
    | '/{-$locale}/auth/register-success'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/demo/better-auth'
    | '/{-$locale}/_marketing/'
    | '/api/payment/notify/creem'
    | '/{-$locale}/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentCreateRoute: typeof ApiPaymentCreateRoute
  ApiPaymentQueryRoute: typeof ApiPaymentQueryRoute
  ApiUserBillingRoute: typeof ApiUserBillingRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiUserSettingsRoute: typeof ApiUserSettingsRoute
  ApiUserSubscriptionRoute: typeof ApiUserSubscriptionRoute
  ApiPaymentNotifyCreemRoute: typeof ApiPaymentNotifyCreemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/_marketing': {
      id: '/{-$locale}/_marketing'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125MarketingRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/_dashboard': {
      id: '/{-$locale}/_dashboard'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_marketing/': {
      id: '/{-$locale}/_marketing/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125MarketingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MarketingRoute
    }
    '/{-$locale}/demo/better-auth': {
      id: '/{-$locale}/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/{-$locale}/demo/better-auth'
      preLoaderRoute: typeof Char123LocaleChar125DemoBetterAuthRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/auth/reset-password': {
      id: '/{-$locale}/auth/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/auth/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/register-success': {
      id: '/{-$locale}/auth/register-success'
      path: '/register-success'
      fullPath: '/{-$locale}/auth/register-success'
      preLoaderRoute: typeof Char123LocaleChar125AuthRegisterSuccessRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/register': {
      id: '/{-$locale}/auth/register'
      path: '/register'
      fullPath: '/{-$locale}/auth/register'
      preLoaderRoute: typeof Char123LocaleChar125AuthRegisterRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/login': {
      id: '/{-$locale}/auth/login'
      path: '/login'
      fullPath: '/{-$locale}/auth/login'
      preLoaderRoute: typeof Char123LocaleChar125AuthLoginRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/forgot-password': {
      id: '/{-$locale}/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/auth/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/confirm': {
      id: '/{-$locale}/auth/confirm'
      path: '/confirm'
      fullPath: '/{-$locale}/auth/confirm'
      preLoaderRoute: typeof Char123LocaleChar125AuthConfirmRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/_marketing/pay-success': {
      id: '/{-$locale}/_marketing/pay-success'
      path: '/pay-success'
      fullPath: '/{-$locale}/pay-success'
      preLoaderRoute: typeof Char123LocaleChar125MarketingPaySuccessRouteImport
      parentRoute: typeof Char123LocaleChar125MarketingRoute
    }
    '/{-$locale}/_marketing/contact': {
      id: '/{-$locale}/_marketing/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125MarketingContactRouteImport
      parentRoute: typeof Char123LocaleChar125MarketingRoute
    }
    '/{-$locale}/_marketing/about': {
      id: '/{-$locale}/_marketing/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125MarketingAboutRouteImport
      parentRoute: typeof Char123LocaleChar125MarketingRoute
    }
    '/api/user/subscription': {
      id: '/api/user/subscription'
      path: '/api/user/subscription'
      fullPath: '/api/user/subscription'
      preLoaderRoute: typeof ApiUserSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/settings': {
      id: '/api/user/settings'
      path: '/api/user/settings'
      fullPath: '/api/user/settings'
      preLoaderRoute: typeof ApiUserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/billing': {
      id: '/api/user/billing'
      path: '/api/user/billing'
      fullPath: '/api/user/billing'
      preLoaderRoute: typeof ApiUserBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/query': {
      id: '/api/payment/query'
      path: '/api/payment/query'
      fullPath: '/api/payment/query'
      preLoaderRoute: typeof ApiPaymentQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/create': {
      id: '/api/payment/create'
      path: '/api/payment/create'
      fullPath: '/api/payment/create'
      preLoaderRoute: typeof ApiPaymentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_dashboard/dashboard/': {
      id: '/{-$locale}/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125DashboardDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/api/payment/notify/creem': {
      id: '/api/payment/notify/creem'
      path: '/api/payment/notify/creem'
      fullPath: '/api/payment/notify/creem'
      preLoaderRoute: typeof ApiPaymentNotifyCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125DashboardRouteChildren {
  Char123LocaleChar125DashboardDashboardIndexRoute: typeof Char123LocaleChar125DashboardDashboardIndexRoute
}

const Char123LocaleChar125DashboardRouteChildren: Char123LocaleChar125DashboardRouteChildren =
  {
    Char123LocaleChar125DashboardDashboardIndexRoute:
      Char123LocaleChar125DashboardDashboardIndexRoute,
  }

const Char123LocaleChar125DashboardRouteWithChildren =
  Char123LocaleChar125DashboardRoute._addFileChildren(
    Char123LocaleChar125DashboardRouteChildren,
  )

interface Char123LocaleChar125MarketingRouteChildren {
  Char123LocaleChar125MarketingAboutRoute: typeof Char123LocaleChar125MarketingAboutRoute
  Char123LocaleChar125MarketingContactRoute: typeof Char123LocaleChar125MarketingContactRoute
  Char123LocaleChar125MarketingPaySuccessRoute: typeof Char123LocaleChar125MarketingPaySuccessRoute
  Char123LocaleChar125MarketingIndexRoute: typeof Char123LocaleChar125MarketingIndexRoute
}

const Char123LocaleChar125MarketingRouteChildren: Char123LocaleChar125MarketingRouteChildren =
  {
    Char123LocaleChar125MarketingAboutRoute:
      Char123LocaleChar125MarketingAboutRoute,
    Char123LocaleChar125MarketingContactRoute:
      Char123LocaleChar125MarketingContactRoute,
    Char123LocaleChar125MarketingPaySuccessRoute:
      Char123LocaleChar125MarketingPaySuccessRoute,
    Char123LocaleChar125MarketingIndexRoute:
      Char123LocaleChar125MarketingIndexRoute,
  }

const Char123LocaleChar125MarketingRouteWithChildren =
  Char123LocaleChar125MarketingRoute._addFileChildren(
    Char123LocaleChar125MarketingRouteChildren,
  )

interface Char123LocaleChar125AuthRouteChildren {
  Char123LocaleChar125AuthConfirmRoute: typeof Char123LocaleChar125AuthConfirmRoute
  Char123LocaleChar125AuthForgotPasswordRoute: typeof Char123LocaleChar125AuthForgotPasswordRoute
  Char123LocaleChar125AuthLoginRoute: typeof Char123LocaleChar125AuthLoginRoute
  Char123LocaleChar125AuthRegisterRoute: typeof Char123LocaleChar125AuthRegisterRoute
  Char123LocaleChar125AuthRegisterSuccessRoute: typeof Char123LocaleChar125AuthRegisterSuccessRoute
  Char123LocaleChar125AuthResetPasswordRoute: typeof Char123LocaleChar125AuthResetPasswordRoute
}

const Char123LocaleChar125AuthRouteChildren: Char123LocaleChar125AuthRouteChildren =
  {
    Char123LocaleChar125AuthConfirmRoute: Char123LocaleChar125AuthConfirmRoute,
    Char123LocaleChar125AuthForgotPasswordRoute:
      Char123LocaleChar125AuthForgotPasswordRoute,
    Char123LocaleChar125AuthLoginRoute: Char123LocaleChar125AuthLoginRoute,
    Char123LocaleChar125AuthRegisterRoute:
      Char123LocaleChar125AuthRegisterRoute,
    Char123LocaleChar125AuthRegisterSuccessRoute:
      Char123LocaleChar125AuthRegisterSuccessRoute,
    Char123LocaleChar125AuthResetPasswordRoute:
      Char123LocaleChar125AuthResetPasswordRoute,
  }

const Char123LocaleChar125AuthRouteWithChildren =
  Char123LocaleChar125AuthRoute._addFileChildren(
    Char123LocaleChar125AuthRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRouteWithChildren
  Char123LocaleChar125MarketingRoute: typeof Char123LocaleChar125MarketingRouteWithChildren
  Char123LocaleChar125AuthRoute: typeof Char123LocaleChar125AuthRouteWithChildren
  Char123LocaleChar125DemoBetterAuthRoute: typeof Char123LocaleChar125DemoBetterAuthRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125DashboardRoute:
    Char123LocaleChar125DashboardRouteWithChildren,
  Char123LocaleChar125MarketingRoute:
    Char123LocaleChar125MarketingRouteWithChildren,
  Char123LocaleChar125AuthRoute: Char123LocaleChar125AuthRouteWithChildren,
  Char123LocaleChar125DemoBetterAuthRoute:
    Char123LocaleChar125DemoBetterAuthRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentCreateRoute: ApiPaymentCreateRoute,
  ApiPaymentQueryRoute: ApiPaymentQueryRoute,
  ApiUserBillingRoute: ApiUserBillingRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiUserSettingsRoute: ApiUserSettingsRoute,
  ApiUserSubscriptionRoute: ApiUserSubscriptionRoute,
  ApiPaymentNotifyCreemRoute: ApiPaymentNotifyCreemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
